import { PatternPreset, Step, Track } from '@/types/sequencer';

function createSteps(patternString: string, pitches: (string | undefined)[], velocities: number[]): Step[] {
  const steps: Step[] = [];
  const total = 16;
  for (let i = 0; i < total; i++) {
    const char = patternString[i % patternString.length] || '.';
    const active = char === 'X' || char === 'x';
    steps.push({
      active,
      velocity: velocities[i % velocities.length] ?? 0.8,
      pitch: pitches[i % pitches.length],
      probability: 1.0,
    });
  }
  return steps;
}

export const FACTORY_PRESETS: PatternPreset[] = [
  {
    id: 'neon-dystopia',
    name: 'Neon Dystopia',
    genre: '128 BPM Synthwave',
    description: 'Pumping cybernetic synth arps, driving 4-on-the-floor kick, and resonant acid lines.',
    bpm: 128,
    rootKey: 'F',
    scale: 'Minor Pentatonic',
    swing: 0,
    fx: {
      cutoff: 4200,
      resonance: 4.5,
      delayTime: '8n',
      delayFeedback: 0.45,
      delayWet: 0.3,
      reverbDecay: 3.2,
      reverbWet: 0.28,
      distortion: 0.25,
      masterVolume: 0,
    },
    tracks: [
      {
        id: 'synth-1',
        name: 'Cyber Poly Synth',
        type: 'synth',
        muted: false,
        solo: false,
        volume: -2,
        pan: -0.2,
        defaultPitch: 'F4',
        steps: createSteps(
          'X.XX.X.XX.XX.X.X',
          ['F4', 'G#4', 'C5', 'D#5', 'F5', 'D#5', 'C5', 'G#4', 'F4', 'C5', 'D#5', 'G#4', 'F5', 'D#5', 'C5', 'A#4'],
          [0.9, 0.6, 0.8, 0.7, 0.95, 0.6, 0.75, 0.65, 0.9, 0.7, 0.85, 0.6, 0.95, 0.7, 0.8, 0.6]
        ),
      },
      {
        id: 'bass-1',
        name: 'Acid Sub Bass',
        type: 'bass',
        muted: false,
        solo: false,
        volume: 0,
        pan: 0,
        defaultPitch: 'F2',
        steps: createSteps(
          'XXXX.XXXXXXX.XXX',
          ['F2', 'F2', 'G#2', 'F2', 'F2', 'C3', 'D#3', 'F2', 'F2', 'F2', 'G#2', 'A#2', 'C3', 'F2', 'D#2', 'C2'],
          [0.95, 0.8, 0.85, 0.75, 0.9, 0.85, 0.9, 0.7, 0.95, 0.8, 0.85, 0.9, 0.95, 0.75, 0.8, 0.7]
        ),
      },
      {
        id: 'kick-1',
        name: 'Punchy 808 Kick',
        type: 'kick',
        muted: false,
        solo: false,
        volume: 2,
        pan: 0,
        steps: createSteps('X...X...X...X...', [undefined], [1.0, 0.9, 1.0, 0.9]),
      },
      {
        id: 'snare-1',
        name: 'Vintage Snare',
        type: 'snare',
        muted: false,
        solo: false,
        volume: -1,
        pan: 0.1,
        steps: createSteps('....X.......X...', [undefined], [0.95]),
      },
      {
        id: 'hihat-1',
        name: 'Crisp Closed Hat',
        type: 'hihat',
        muted: false,
        solo: false,
        volume: -4,
        pan: 0.3,
        steps: createSteps('.X.X.X.X.X.X.X.X', [undefined], [0.6, 0.8, 0.55, 0.85, 0.6, 0.8, 0.65, 0.9]),
      },
      {
        id: 'perc-1',
        name: 'Cyber Perc Ping',
        type: 'perc',
        muted: false,
        solo: false,
        volume: -3,
        pan: -0.35,
        steps: createSteps('..X...X...X...X.', [undefined], [0.75, 0.85, 0.7, 0.9]),
      },
    ],
  },
  {
    id: 'deep-rain',
    name: 'Deep Rain',
    genre: '84 BPM Lo-Fi Ambient',
    description: 'Lush reverb tails, melancholic pentatonic swells, and textured organic percussion.',
    bpm: 84,
    rootKey: 'D',
    scale: 'Dorian',
    swing: 0.25,
    fx: {
      cutoff: 1800,
      resonance: 2.0,
      delayTime: '8t',
      delayFeedback: 0.65,
      delayWet: 0.45,
      reverbDecay: 6.5,
      reverbWet: 0.55,
      distortion: 0.08,
      masterVolume: -1,
    },
    tracks: [
      {
        id: 'synth-1',
        name: 'Lofi Tape Keys',
        type: 'synth',
        muted: false,
        solo: false,
        volume: -1,
        pan: -0.25,
        defaultPitch: 'D4',
        steps: createSteps(
          'X...X...X...X...',
          ['D4', 'F4', 'A4', 'C5', 'E5', 'A4', 'G4', 'F4'],
          [0.7, 0.65, 0.75, 0.6, 0.8, 0.55, 0.7, 0.6]
        ),
      },
      {
        id: 'bass-1',
        name: 'Sub Warmth',
        type: 'bass',
        muted: false,
        solo: false,
        volume: -2,
        pan: 0,
        defaultPitch: 'D2',
        steps: createSteps(
          'X.......X.......',
          ['D2', 'G2', 'A2', 'D2'],
          [0.85, 0.8, 0.75, 0.9]
        ),
      },
      {
        id: 'kick-1',
        name: 'Mellow LoFi Kick',
        type: 'kick',
        muted: false,
        solo: false,
        volume: 0,
        pan: 0,
        steps: createSteps('X.....X...X.....', [undefined], [0.85, 0.75, 0.8]),
      },
      {
        id: 'snare-1',
        name: 'Soft Rim Click',
        type: 'snare',
        muted: false,
        solo: false,
        volume: -3,
        pan: 0.15,
        steps: createSteps('....X.......X...', [undefined], [0.7, 0.75]),
      },
      {
        id: 'hihat-1',
        name: 'Shuffled Hat',
        type: 'hihat',
        muted: false,
        solo: false,
        volume: -5,
        pan: 0.2,
        steps: createSteps('X.XXX.XXX.XXX.XX', [undefined], [0.5, 0.7, 0.4, 0.6, 0.45, 0.65, 0.5, 0.7]),
      },
      {
        id: 'perc-1',
        name: 'Water Texture Perc',
        type: 'perc',
        muted: false,
        solo: false,
        volume: -4,
        pan: -0.3,
        steps: createSteps('..X...X.....X...', [undefined], [0.6, 0.7, 0.65]),
      },
    ],
  },
  {
    id: 'berlin-basement',
    name: 'Berlin Basement',
    genre: '134 BPM Minimal Acid',
    description: 'Relentless hypnotic 303 squelch, tight clicky drums, and industrial tape distortion.',
    bpm: 134,
    rootKey: 'A',
    scale: 'Phrygian',
    swing: 0,
    fx: {
      cutoff: 2800,
      resonance: 8.5,
      delayTime: '16n',
      delayFeedback: 0.35,
      delayWet: 0.2,
      reverbDecay: 2.0,
      reverbWet: 0.18,
      distortion: 0.5,
      masterVolume: 1,
    },
    tracks: [
      {
        id: 'synth-1',
        name: 'Industrial Drone',
        type: 'synth',
        muted: false,
        solo: false,
        volume: -3,
        pan: 0.3,
        defaultPitch: 'A3',
        steps: createSteps(
          'X...X...X...X.X.',
          ['A3', 'A#3', 'D4', 'E4', 'A4', 'G4', 'E4', 'A#3'],
          [0.8, 0.6, 0.85, 0.7, 0.9, 0.75, 0.65, 0.8]
        ),
      },
      {
        id: 'bass-1',
        name: 'TB-303 Acid Lead',
        type: 'bass',
        muted: false,
        solo: false,
        volume: 2,
        pan: 0,
        defaultPitch: 'A1',
        steps: createSteps(
          'XXXXXXXXXXXXXXXX',
          ['A1', 'A1', 'A#1', 'A1', 'E2', 'A1', 'D2', 'C2', 'A1', 'A2', 'A#1', 'A1', 'G1', 'A1', 'E2', 'A#1'],
          [0.9, 0.7, 0.95, 0.6, 1.0, 0.65, 0.85, 0.7, 0.9, 0.95, 0.8, 0.6, 0.85, 0.7, 1.0, 0.75]
        ),
      },
      {
        id: 'kick-1',
        name: 'Industrial 909 Kick',
        type: 'kick',
        muted: false,
        solo: false,
        volume: 3,
        pan: 0,
        steps: createSteps('X...X...X...X...', [undefined], [1.0]),
      },
      {
        id: 'snare-1',
        name: 'Clap Stack',
        type: 'snare',
        muted: false,
        solo: false,
        volume: 0,
        pan: 0,
        steps: createSteps('....X.......X...', [undefined], [0.95]),
      },
      {
        id: 'hihat-1',
        name: 'Off-beat Open Hat',
        type: 'hihat',
        muted: false,
        solo: false,
        volume: -2,
        pan: 0.25,
        steps: createSteps('..X...X...X...X.', [undefined], [0.85, 0.9, 0.85, 0.95]),
      },
      {
        id: 'perc-1',
        name: 'Metal Resonator',
        type: 'perc',
        muted: false,
        solo: false,
        volume: -2,
        pan: -0.25,
        steps: createSteps('.X.X.X.X.X.X.X.X', [undefined], [0.55, 0.75, 0.6, 0.8, 0.55, 0.7, 0.65, 0.85]),
      },
    ],
  },
  {
    id: 'solar-winds',
    name: 'Solar Winds',
    genre: '100 BPM Space Electronica',
    description: 'Cosmic Japanese Hirajoshi melodies, floating delay matrices, and ethereal polyrhythmic textures.',
    bpm: 100,
    rootKey: 'G',
    scale: 'Hirajoshi',
    swing: 0.1,
    fx: {
      cutoff: 6500,
      resonance: 3.0,
      delayTime: '8n',
      delayFeedback: 0.55,
      delayWet: 0.4,
      reverbDecay: 5.5,
      reverbWet: 0.45,
      distortion: 0.12,
      masterVolume: 0,
    },
    tracks: [
      {
        id: 'synth-1',
        name: 'Cosmic Pluck',
        type: 'synth',
        muted: false,
        solo: false,
        volume: 0,
        pan: -0.15,
        defaultPitch: 'G4',
        steps: createSteps(
          'X..X..X.X..X..X.',
          ['G4', 'G#4', 'C5', 'D5', 'D#5', 'G5', 'D#5', 'D5', 'C5', 'G#4', 'G4', 'D5', 'G5', 'D#5', 'C5', 'G4'],
          [0.9, 0.7, 0.85, 0.75, 0.95, 0.7, 0.8, 0.65, 0.9, 0.75, 0.85, 0.7, 0.95, 0.8, 0.85, 0.7]
        ),
      },
      {
        id: 'bass-1',
        name: 'Deep Orbit Mono',
        type: 'bass',
        muted: false,
        solo: false,
        volume: -1,
        pan: 0,
        defaultPitch: 'G2',
        steps: createSteps(
          'X......XX......X',
          ['G2', 'D#2', 'C2', 'G2', 'G#2', 'G2', 'D2', 'G2'],
          [0.9, 0.8, 0.85, 0.9, 0.75, 0.85, 0.8, 0.9]
        ),
      },
      {
        id: 'kick-1',
        name: 'Deep Sine Kick',
        type: 'kick',
        muted: false,
        solo: false,
        volume: 1,
        pan: 0,
        steps: createSteps('X.......X.......', [undefined], [0.95, 0.9]),
      },
      {
        id: 'snare-1',
        name: 'Stardust Snare',
        type: 'snare',
        muted: false,
        solo: false,
        volume: -2,
        pan: 0.2,
        steps: createSteps('....X.......X...', [undefined], [0.85, 0.9]),
      },
      {
        id: 'hihat-1',
        name: 'Celestial Shimmer',
        type: 'hihat',
        muted: false,
        solo: false,
        volume: -4,
        pan: 0.35,
        steps: createSteps('XXXXXXXX.XXXXXXX', [undefined], [0.5, 0.75, 0.55, 0.8, 0.6, 0.7, 0.55, 0.85]),
      },
      {
        id: 'perc-1',
        name: 'Crystal Chime Perc',
        type: 'perc',
        muted: false,
        solo: false,
        volume: -2,
        pan: -0.3,
        steps: createSteps('..X...X...X...X.', [undefined], [0.75, 0.85, 0.7, 0.9]),
      },
    ],
  },
];
